chore: don't mark candidate requests as processing
ceramicnetwork/ceramic-anchor-service pull request #577
Opened 2022-02-02 16:07 UTC by stephhuynh18

# Don't mark candidate requests as processing

## Description

I did not remove the processing status as it may be used in the future when we decide to run CAS instances in parallel. 

## How Has This Been Tested?

Tests are running

2022-02-02 22:47 UTC, stbrody requested changes
Can we rename the `PROCESSING` status to `DEPRECATED_PROCESSING`?
 https://github.com/ceramicnetwork/ceramic-anchor-service/blob/b1977d8555860527eaf43e3411fbfa0661207848/src/models/request-status.ts#L3

2022-02-02 22:47 UTC, stbrody commented on src/services/anchor-service.ts
>        await this.requestRepository.updateRequests(
I think we should remove this update entirely.  It does mean that if we crash some streams may be pinned that aren't marked that way in the database, but that's already the case today, this just makes that window slightly larger.  But in the vast majority of cases, those streams will be picked up in the next batch and if that batch finishes successfully then the state will be correct.

This update slows things down and floods the logs, for very little real value.

2022-02-02 22:50 UTC, stbrody commented
We should also update `findNextToProcess` to remove the special casing of the PROCESSING status: https://github.com/ceramicnetwork/ceramic-anchor-service/blob/b1977d8555860527eaf43e3411fbfa0661207848/src/repositories/request-repository.ts#L96

and update the README to remove references to PROCESSING.

2022-02-02 23:24 UTC, stephhuynh18 commented
@stbrody yup sounds good. I wasn't sure if we just wanted to "pause" the status or deprecate it. I'll have those changes in shortly.

2022-02-21 22:29 UTC, stbrody approved these changes
LGTM, but let's hold off on merging this until the CAS is working on dev again to avoid destabilizing any further

2022-02-21 22:29 UTC, stbrody commented on src/repositories/request-repository.ts
>        .createQueryBuilder('request')
can remove `now` and `deadlineDate` above now as they are no longer used

2022-03-04 15:54 UTC, merged