[DRAFT] working implementation of phase 3
ceramicnetwork/ceramic-anchor-service pull request #678
Opened 2022-07-11 13:25 UTC by Jovonni

# Indexable Anchors Phase 3 - #[Issue]

## Description
Working implementation of phase 3 of the indexable anchors work

# Gas Consumption with calldata
Due to the length of the hex encoded cid, the payload is encoded the pattern `<sig>` `<location>` `<length>` `<param>` since the bytes type is dynamically sized 

calldata example, where `0x7d3b0ca2` is the function sign
```
0x7d3b0ca2000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000260f01850112204a427b02b719082b0440459d7cfad2187ee96cf3a3c2c72deac1234724b3a3460000000000000000000000000000000000000000000000000000
```

Also, the actual function paramater is padded to the right.

Include a summary of the change and which issue it addresses in the title of the PR. 

Include relevant motivation, context, brief description and impact of the change(s). List follow-up tasks here.

## How Has This Been Tested?

Describe the tests that you ran to verify your changes. Provide instructions for reproduction.

- [ ] Test A (e.g. Test A - New test that ... ran in local, docker, and dev unstable.)
- [ ] Test B

## Definition of Done

Before submitting this PR, please make sure:

- [ ] The work addresses the description and outcomes in the issue
- [ ] I have added relevant tests for new or updated functionality
- [ ] My code follows conventions, is well commented, and easy to understand
- [ ] My code builds and tests pass without any errors or warnings
- [ ] I have tagged the relevant reviewers
- [ ] I have updated the READMEs of affected packages
- [ ] I have made corresponding changes to the documentation
- [ ] The changes have been communicated to interested parties

## References:

Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.

2022-07-15 12:37 UTC, ukstv requested changes
Please, re-request a review, when the PR is ready.

FYI: While it is in draft, you could take someone's attention by pinging that person in a single comment on a line of interest.

2022-07-15 12:37 UTC, ukstv commented on .env.prod.example
> +xETH_GAS_LIMIT=4712388
What does this `xETH` do?

2022-07-15 12:37 UTC, ukstv commented on config/default.json
> +  "cronExpressionx": "0/5 * * * ? *",
What is `cronExpressionx` here? How does it compare to `cronExpression`?

2022-07-15 12:37 UTC, ukstv commented on contracts/src/CeramicAnchorServiceV2.sol
> +    // event DidAnchor(address indexed _service, bytes32 _root);
dev comments.

In the future, please, make sure to not leave dev artefacts like this in the PRs. It is quite annoying.

2022-07-15 12:37 UTC, ukstv commented on contracts/src/CeramicAnchorServiceV2.sol
> +    // TODO: upon contract creation, allowList is blank, so nobody is allowed
If you have a TODO like this, please, accompany it with a corresponding Linear issue, which tracks the fix.

Like this: `TODO(NET-NNNN): upon ....`

2022-07-15 12:37 UTC, ukstv commented on contracts/src/CeramicAnchorServiceV2.sol
> +        // TODO: should we add owner address to allowList upon contract creation
Again, TODO should have a corresponding Linear issue.

2022-07-15 12:37 UTC, ukstv commented on contracts/src/CeramicAnchorServiceV2.sol
> +    // function anchor(bytes32 calldata _root1, bytes32 calldata _root2, bytes8 calldata _root3) public onlyAllowed {
It is a dev artefact, isn't it?

2022-07-15 12:37 UTC, ukstv commented on logfile
> +2022-06-26 10:13:19.614 EDT [82777] LOG:  starting PostgreSQL 14.2 on aarch64-apple-darwin21.3.0, compiled by Apple clang version 13.0.0 (clang-1300.0.29.30), 64-bit
Should it be part of the PR? Should it be git-ignored?

2022-07-15 12:37 UTC, ukstv commented on package.json
> +    "ganache": "^7.3.2",
Is `ganache` a newer version of `ganache-core`? If so, maybe it makes sense to drop `ganache-core`.

2022-07-15 12:37 UTC, ukstv commented on src/__tests__/ceramic_integration.test.ts
> +import ganache from "ganache"
Is it even used here?

2022-07-15 19:03 UTC, stephhuynh18 commented on src/__tests__/ceramic_integration.test.ts
> +  //todo
You will also need to set `useSmartContractAnchors` to true

2023-01-04 22:02 UTC, stbrody commented
@stephhuynh18 should this PR be closed?  Is there anything in here that wasn't already merged in a different PR?

2023-01-04 23:29 UTC, stephhuynh18 commented
@stbrody closing

2023-01-04 23:29 UTC, closed without merging